== Using the Github API

Once you know how you want to setup a work flow you may wish to
automate some or all of it, to make the life of your team easier. This
way you can provide a set of tools, which can be run from a command
line, as plug ins for your favorite tool, or as part of a web
interface.

Of course as git is a command line tool a shell script can be written
that will do many of the standard git operations. So for example you
could take some raw data, populate some templates, commit them into
git and push them up to a server. 

NOTE: TODO talk about github's web hosting

However if you want to do something more complex then you may wish to
use the github api which lets you access many of the features of
github programmaticly instead of doing them via the web interface.

NOTE: TODO a few more examples


BLAH BLAH BLAH

=== Building a Delta Debugger

If you have a comprehensive set of tests it can be possible to 
build a tool to allow you to very easily zero in on a fault if one
gets introduced into the system. If someone has pushed a set of
changes into a project then those changes may have affected dozens of
files and hundreds of tests. In addition there may have been 50 or
more commits in that change set.

If you know that tests start failing then it would be possible to roll
back to the last commit which all tests pass then by moving forward
one commit at a time unit a test fails. At that point we can see
which lines in which files have changed, and what lines of code are
covered by the failing tests.

What we want is is to know is which lines are in common between the
changes and the coverage of the failing tests. If the commits are
small changes and the coverage of each test is tight then in many
cases the developer can be directed to an area of 1-2 lines of code
where the bug exists.

+++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++++++++++++++

=== A Build Tool

An automated build tool...

=== CI with github

If you are using github for hosting your product you may wish to do
Continous Integration with your github repository.


NOTE: TODO how to do this

















