== Graphical Git Front-ends

I will confess to being a long time linux and Emacs user. As such
moving from CVS and SVN to GIT and HG was pretty easy. The Emacs VCS
modes for all four systems are pretty similar and the same basic
keystrokes will work on all of them. (Which is really quite handy when
you have to switch back and forth for different projects). 

In addition I have long experience with command lines so using a unix
bash shell to get things done is not a big deal for me. Of course not
everyone will wish to work with a command line tool (or to do so for
all tasks). As such there are a number of tools for both the Mac and
Windows that can make your life easier. 

In order to be included here a package must be free and include all of
the normal git commands that you might want to use from a command
line. 
za
=== Windows 
==== Tortoise GIT

If you have used the Tortoise Client for CVS or SVN you will be
happy to know that they also have a GIT client.

==== Tortoise HG


==== Github For windows?


=== Mac

There are a number of graphical git tools for the mac. You can of
course download the command line git via homebrew (and probably
should) but if you want to do some things with a graphical client
there are a few free options. 

==== Github For Mac

The folks at Github, as part of their effort to improve the git
ecosystem have their own Git client for the mac, You can download it
from link:http://mac.github.com/[] or by going to
link:http://www.github.com[] and selecting Github for Mac at the
bottom of the page. 

Note: you do not need to use github for mac only with Github, it will
work with any git repository. So if you host your public projects on
github and your private ones on bitbucket you can use this tool with
both. However some features may only work with github

The github mac client will of course do everything you would expect a
git client to do. It can commit changes, view history, create and
merge branches and so on. 

==== Sourcetree
