== Introducing Git and HG

This book is not about version control. That is a radical statement as
it says "Using Git and Mercurial" on the cover, but its not about git
or mercurial, nor is it about software development, though most of the
readers will be software developers. What this book is about is teams.

Its not just software, many things worth doing these days are done by
teams of people. While most people who use GitHub are programmers
and will use it to write programs. 

GitHub can be used (And for
those of you who know nothing about knitting, to say knitters are
passionate about what they do would be an understatement)

=== Thanks

This book was envisioned as a collaborative project. I wanted to hear
how other people have collaborated on projects, find out what works
and what doesn't.

In developing this book I have to thank several people, First of all
Simon St Lawrence and Andy Oram at O'Reilly Media who have supported
me.

Matthew McCullough of the GitHub training group has offered me a
number of suggestions as well as promoted this book within GitHub.

In addition a number of people have sent me pull requests with
changes. Contributors are listed here in alphabetical order by GitHub user
name.

* breskeby - Rene Groeschke
* kirean   - Erik Andersson
* rkessin  - Richard Kessin
