== Working as a Solo Developer with a Client

[grid="rows",format="csv"]
[options="header",cols="<s,<,<"]
|===========================

Team Members, *Well Defined* , Amorphous
Team Location, *Distributed*, Co Located
Time Frame, On Going, *Limited*
Team Size, Large, *Small*
Leadership, Formal, *Informal*
|===========================

If you ar e a freelance software consultant (which I am) and you need
to work with clients a lot on projects then you will need to vary the
previous pattern for working with your clients.  

In this case the team is well defined, you the consultant and the
client. The scope is probably limited to one short project, and
the leadership structure is pretty simple based on just you and the
client. 

In this case, generally the developer will probably be commiting most
of the changes to the code or content and the client will be reviewing
them, but possibly also submitting some content from time to time,
which could involve setting configuration options or uploading artwork
or the like. (Clearly this will change based on the exact nature of
the consultant client relationship). 

In this case the easist way to structure the project is probably to
open a repository at Github or Bitbucket and share it with the
client so that you both have read / write access, it would be possible
to fork a repo for the client and send pull requests back and forth
but it is probably more trouble than it is worth. 
