== Using HG

While GIT is the major DVCS in use Murcuial (also known as hg) is also
being used by a number of projects. In many cases the basic ideas of
git and HG are pretty similar, so if you have been using one switching
to the other should not require much of a learning curve.

NOTE: HG is the chemical symbol for mercury, so that is the short
name. All those of you who remember high school or college chemistry
class knew that. 

There are of course a number of technical differences in the internal
workings of git and HG but they are beyond the scope of this book as I
really want to focus on how to effectively use these tools to get work
done. How the internals work are not really important, if you care of
course then there are a number of books, videos and web sites that
will cover that.

To create a repository in HG create a directory and use the command
+hg init+. This will create an empty hg repository to which we can add
files.

If we want to share that repository we can run the command +hg serve+
which will open a web server on port 8000 which we can use the
interact with the hg repository. 

NOTE: run +hg serve+ will by default not run in the background but
keep logging to the terminal, so run it on a spare tab on in a session
with screen or tmux or the like. 

------
listening at http://Galileo.local:8000/ (bound to *:8000)
127.0.0.1 - - [15/Sep/2012 21:50:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2012 21:50:31] "GET /static/style-paper.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2012 21:50:31] "GET /static/mercurial.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2012 21:50:31] "GET /static/hglogo.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2012 21:50:31] "GET /static/hgicon.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2012 21:51:06] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [15/Sep/2012 21:51:06] "GET /static/style-paper.css HTTP/1.1" 304 -
127.0.0.1 - - [15/Sep/2012 21:51:06] "GET /static/mercurial.js HTTP/1.1" 304 -
127.0.0.1 - - [15/Sep/2012 21:51:06] "GET /static/hglogo.png HTTP/1.1" 304 -
127.0.0.1 - - [15/Sep/2012 21:51:06] "GET /static/hgicon.png HTTP/1.1" 304 -
------

