== Workflow Planning

One of the great advantages of a DVCS is that there is not one
prescribed workflow. Teams are free to figure out what will work best
for them. The great disadvantage is that since there is not one
prescribed workflow teams have to figure that out.

In addition as a project and team evolve the ideal workflow may change
over time. 


To figure out what type of work flow several questions will have to be
asked. There are several attributes of a project and a team that have
to be asked as shown on this table. 

[grid="rows",format="csv"]
[options="header",cols="<s,<,<"]
|===========================

Team Members, Well Defined , Amorphous
Team Location, Distributed, Co Located
Time Frame, On Going, Limited
Team Size, Large, Small
Leadership, Formal, Informal
|===========================

Of course many projects will hit somewhere in the middle on one or
those questions. The Linux Kernel team is probably pretty well defined
at the core but may be a bit Amorphous at the edges. Each workflow
presented here will start with a version of this chart for reference.  
