== Workflow Planning

One of the great advantages of a DVCS is that there is not one
prescribed workflow. Teams are free to figure out what will work best
for them. The great disadvantage is that since there is not one
prescribed workflow teams have to figure that out.


To figure out what type of work flow several questions will have to be
asked. There are several attributes of a project and a team that have
to be asked as shown on this table. 

[grid="rows",format="csv"]
[options="header",cols="<s,<,<"]
|===========================

Team Members, Well Defined , Amorphous
Team Location, Distributed, Co Located
Time Frame, On Going, Limited
Team Size, Large, Small
Leadership, Formal, Informal
|===========================

Of course many projects will hit somewhere in the middle on one or
those questions. The Linux Kernel team is probably pretty well defined
at the core but may be a bit amorphous at the edges. Each workflow
presented here will start with a version of this chart for
reference. 

It should also be noted that a work flow does not have to stay the
same over the course of a project. If three friends decide to create a
startup when they first start it will probably be three people with
laptops writing code late into the evenings over Pizza. If they are
successful the team will grow and they may find that what they have
been doing so far does not work well for them. In this case they will
want to adapt to a new setup. 

The advantage of a DVCS is that these kind of changes are at least
from a technical point of view pretty simple to handle. Repositories
can be cloned and merged pretty much at will. 
  
