=== A Public or Open Source Project

[grid="rows",format="csv"]
[options="header",cols="<s,<,<"]
|===========================
Team Members, Well Defined , *Amorphous*
Team Location, *Distributed*, Co Located
Time Frame, *On Going*, Limited
Team Size, *Large*, Small
Leadership, Formal, *Informal*
Repository Access, *Public*, Private
|===========================


A public project, including many open source programs, is one where
you are trying to leverage the community at large to build
something. This may be a book (like this one), or a open source
software project or even a families collection of recipes. 

In this case GitHub is a clear win just by its large community and its
tools to create and support community. 

In terms of how to work it is pretty simple, the project leader will
publish a repository on GitHub and then announce it (normally via
twitter, blogs, mailing lists or other social media sites).

At this point anyone else who is interested in the project will then
fork the repository and add their own content. This will be sent back
to the original leader via a pull request. 

If the project gets large then it may evolve into something that
resembles the Linux Kernel team work flow. This is in effect a
simplified version of that pattern. While the Linux kernel team has
several layers of gate keeper between a contributer and the
authoritative version of the project, in a smaller project there may
only be one or two core people who accept all the pull requests and
integrate them. 
