=== Working as a Solo Developer with a Client

[grid="rows",format="csv"]
[options="header",cols="<s,<,<"]
|===========================
Team Members, *Well Defined* , Amorphous
Team Location, *Distributed*, Co Located
Time Frame, On Going, *Limited*
Team Size, Large, *Small*
Leadership, Formal, *Informal*
Repository Access, Public, *Private*
|===========================

If you are a free lance software consultant (which I am) and you need
to work with clients a lot on projects then you will need to vary the
previous pattern for working with your clients.  

In this case the team is well defined, you the consultant and the
client. The scope is probably limited to one short project, and
the leadership structure is pretty simple based on just you and the
client. 

In this case, generally the developer will probably be committing most
of the changes to the code or content and the client will be reviewing
them, but possibly also submitting some content from time to time,
which could involve setting configuration options or uploading artwork
or the like. (Clearly this will change based on the exact nature of
the consultant client relationship). 

In this case the easiest way to structure the project is probably to
open a repository at GitHub or Bitbucket and share it with the
client so that you both have read / write access, it would be possible
to fork a repo for the client and send pull requests back and forth
but it is probably more trouble than it is worth. 

I find that when working in this small a group many of the
notification features that are present in GitHub or Bitbucket can be
dealt with by simply picking up my phone and calling my client, or by
using some form of IM. Of course that does not mean that project
notifications are not useful, so much as that using them may not be
required in such a small team. 

